### ISSUE TITLE
Icon missing on start conversation button

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#546] opened 2018-04-23 14:58 UTC
![screen shot 2018-04-23 at 9 57 21 am](https://user-images.githubusercontent.com/32306910/39134701-d73f190e-46dc-11e8-8b9d-9c2c5849b583.png)

**Comment by lilalien** [comment] 2018-04-23 15:03
I can confirm this, funny how I never noticed this one!

**Comment by lilalien** [comment] 2018-04-23 15:05
Looks like it just doesn't have any code, just the placeholder "message" text...

`.button.button--icon--conversation .button-text:before, a.button.button--icon--conversation .button-text:before {
    display: inline-block;
    font: normal normal normal 18px/1 "Material Design Icons";
    font-size: inherit;
    text-rendering: auto;
    line-height: 1;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    transform: translate(0, 0);
    width: auto !important;
    content: 'message';
}`

**Comment by Ian-Hitt** [comment] 2018-04-23 18:14
duplicate, closing

**Closed by Ian-Hitt** 2018-04-23 18:14 UTC
Labels: bug
