### ISSUE TITLE
Tooltip for thread preview off center

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#615] opened 2018-05-16 15:15 UTC
<img width="911" alt="screen shot 2018-05-16 at 10 14 49 am" src="https://user-images.githubusercontent.com/1217271/40126049-fea6a2f6-58f1-11e8-86aa-5cd392bad4a4.png">

**Comment by Ian-Hitt** [comment] 2018-05-16 15:40
@mikecreuzer this is a static position in XF, not a bug in UI.X
<img width="832" alt="screen shot 2018-05-16 at 10 40 20 am" src="https://user-images.githubusercontent.com/15836384/40127690-92e08768-58f5-11e8-8f8d-b0f860dca09e.png">

**Comment by Ian-Hitt** [comment] 2018-05-16 15:40
Can assign to Kyler if you want to change the JS to center on text or something

**Comment by mikecreuzer** [comment] 2018-05-16 15:42
<img width="686" alt="screen shot 2018-05-16 at 10 41 49 am" src="https://user-images.githubusercontent.com/1217271/40127758-c227fa7e-58f5-11e8-8740-e343e352ab09.png">

XenFOro.com ^

**Closed** 2018-05-16 16:27 UTC
