### ISSUE TITLE
UI.X Pro - navigation logo

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#713] opened 2018-06-23 15:30 UTC
add option can disable navigation 2nd logo and only show up when scrolling on Sticky navigation.

![screenshot00055](https://user-images.githubusercontent.com/6899856/41811167-d632c5b6-770a-11e8-9abb-57e262ae73c8.png)

**Comment by Ian-Hitt** [comment] 2018-06-27 22:14
@Nirjonadda IIRC We've this is a duplicate of an issue that we've already discussed. Can you please tell me what you have for Header and Navigation > Minimum viewport width to show logo block. (It cannot be a percentage which I think is what you were using.)

**Comment by Nirjonadda** [comment] 2018-06-27 22:17
Header and Navigation > Minimum viewport width to show logo block is 150%

**Comment by Ian-Hitt** [comment] 2018-06-27 22:36
@Nirjonadda It cannot be a percentage. The screen is always 100% of itself. Use a pixel value instead.

**Closed by Ian-Hitt** 2018-06-27 22:36 UTC
Labels: Bug, Unable to replicate
