### ISSUE TITLE
Floating action button missing - UIX 2 - 2.0.10

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2theme-issues#830] opened 2018-09-21 22:21 UTC
Style Name: UIX 2

Style Version: 2.0.10

UI.X Add-on Version: 2.0.8. beta 1

XenForo Version: 2.0.10

Operating System (and Version):

Browser Name (and Version):

Can you replicate this issue on our demo for this theme?

Does this issue happen in the default XenForo style?

Summary of issue:

I don't know if by design or not but the floating action button is missing from message (post) view now. This is different from previous version.

Go to any thread, for example here: https://canadiancorvetteforums.com/threads/what-to-do-with-your-c5-this-weekend-just-drift-on-by.21258/

**Comment by Ian-Hitt** [comment] 2018-09-28 19:53
The issue is the reply button is just missing in general, fixed in another issue

**Closed by Ian-Hitt** 2018-09-28 19:53 UTC
Labels: Bug
