### ISSUE TITLE
Canvas (sidebar?) showing behind blur effect

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#851] opened 2018-10-19 03:02 UTC
https://xenforo.com/community/threads/ui-x-2-dark-paid.137958/page-11#post-1289579

**Comment by Ian-Hitt** [comment] 2018-10-22 20:28
Duplicate of closed issue https://github.com/Audentio/xf2theme-issues/issues/833

**Closed by Ian-Hitt** 2018-10-22 20:28 UTC
Labels: Bug
