### ISSUE TITLE
Tactical - Remove forum list page actions

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#426] opened 2018-01-17 18:15 UTC
Style Name: Tactical

Disabling Remove forum list page actions then Remove Title from Forum Index are not function. Also Disabling Remove Title from Forum Index are not show the title. Title only showing when Disabled Remove forum list page actions.

**Comment by Ian-Hitt** [comment] 2018-01-17 18:16
@Nirjonadda this is a duplicate of a fixed bug in UI.X that will be availalble in the next release.

**Closed by Ian-Hitt** 2018-01-17 18:16 UTC
