### ISSUE TITLE
Settings cog icon for search not working

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2theme-issues#8] opened 2017-07-25 17:45 UTC
<img width="143" alt="28583987-ba87ba32-7130-11e7-98b9-fc7dc34bc9fe" src="https://user-images.githubusercontent.com/179180/28585790-10a83558-7137-11e7-8252-07b229d762b9.png">

**Comment by Ian-Hitt** [comment] 2017-07-25 18:16
This is a duplicate of 16

**Closed by Ian-Hitt** 2017-07-25 18:16 UTC
