### ISSUE TITLE
Mobile sidenav for secondary buttons (Members, media) not loading in Prisma

### ISSUE THREAD

**Issue by wleffert** [Audentio/xf2theme-issues#1141] opened 2019-10-22 14:17 UTC
Style Name: Prisma

Style Version: 2.1.4.0.0

UI.X Add-on Version: 2.1.2 Patch Level 3

XenForo Version: 2010470

Operating System (and Version): Windows 10 Pro 1903 (build 18362.418), Android 10 (Pixel 3, all updates installed as Google has released)

Browser Name (and Version): Chrome 77.0.3865.120 

Can you replicate this issue on our demo for this theme? Nope; works fine on demo board;

Does this issue happen in the default XenForo style? No

Summary of issue: A side nav that should appear when the members button is clicked on the members page doesn't appear (on mobile devices). Also affects any other page that has a similar side nav. Doesn't affect main side navigation or regular navigation.

Detailed steps to reproduce the issue: On mobile, go to the Members page and click on the "Members" button in the middle above the members list (header for page is "Notable Members"). Same issue is on Media and Resources pages. This happened for a customer, as well as on my local install (unmodified) and Dalton's board: https://demo.themehouse.com/people/dalton/index.php?members/

Additional notes: It could be that notices/lack thereof are interfering, too. When testing on Dalton's board on my Pixel 3, not logged in, I could OCCASIONALLY get it to work; first I accepted the cookie notice, and it worked once. Then it didn't work again.

Upload any screenshots related to the issue below

![2019-10-22-PrismaSidenavBug-1](https://user-images.githubusercontent.com/54987757/67294300-45414080-f4ab-11e9-997c-31f844bde9ea.PNG)
![2019-10-22-PrismaSidenavBug-2-ActiveClick](https://user-images.githubusercontent.com/54987757/67294301-45414080-f4ab-11e9-9844-b330eba23856.PNG)

**Comment by LukasWieditz** [comment] 2019-10-29 12:37
Duplicate of #1143

**Closed by LukasWieditz** 2019-10-29 12:37 UTC
