### ISSUE TITLE
Drift - Notification bubble alignment to close to media's navigation link

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#807] opened 2018-09-18 14:33 UTC
![drift-issue-eight](https://user-images.githubusercontent.com/32306910/45694892-d7974800-bb25-11e8-8053-6005ec538ba1.png)

**Comment by Ian-Hitt** [comment] 2018-09-18 17:59
This is a duplicate of https://github.com/Audentio/xf2theme-issues/issues/782

**Closed by Ian-Hitt** 2018-09-18 17:59 UTC
Labels: Bug
