### ISSUE TITLE
Last post has additional line-break/margin

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#569] opened 2018-04-24 15:27 UTC
<img width="294" alt="screen shot 2018-04-24 at 10 26 21 am" src="https://user-images.githubusercontent.com/1217271/39197416-0377a5b8-47aa-11e8-9cd5-56818eafaa9c.png">

Affects all themes

**Comment by Ian-Hitt** [comment] 2018-04-24 16:04
its not an additional line break, its simply table cells conforming to the other table cells heights. default XF thing
<img width="606" alt="screen shot 2018-04-24 at 11 04 25 am" src="https://user-images.githubusercontent.com/15836384/39199530-4eafacb0-47af-11e8-902d-1265db99ecf8.png">

**Comment by Ian-Hitt** [comment] 2018-04-24 16:07
actually, looks like it is a bug caused by Reactions adding an unnecessary clearfix

**Comment by Ian-Hitt** [comment] 2018-04-24 16:07
moving to add-ons repo

**Closed** 2018-04-24 16:09 UTC
