### ISSUE TITLE
iO - Select for moderation opens thread

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2theme-issues#950] opened 2018-12-05 22:09 UTC
Style Name:
iO
XenForo Version:
v2.0.10

Does this issue happen in the default XenForo style?
No
Summary of issue:
Selection for moderation opens thread.
Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below
https://i.imgur.com/SQJn6GK.gifv

**Comment by Ian-Hitt** [comment] 2018-12-27 21:54
Duplicate of https://github.com/Audentio/xf2theme-issues/issues/966, closing

**Closed by Ian-Hitt** 2018-12-27 21:54 UTC
