### ISSUE TITLE
The floating action button doesn't work in Q&A threads

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xf2theme-issues#455] opened 2018-02-03 22:20 UTC
Style Name: UI.X
Style Version: 2.0.2.1.0
UI.X Add-on Version: 2.0.5 PL1
XenForo Version: 2.0.2
Operating System (and Version): Windows 10 x64
Browser Name (and Version): Chrome, Firefox and Edge
Does this issue happen in the default XenForo style? No

Summary of issue:
Enable the floating action button, install the Q&A addon and then create a Q&A thread.

![action_button](https://user-images.githubusercontent.com/26636634/35772076-fcaecb34-092f-11e8-9e02-081360e23ee9.png)

The floating action button will look like this and when you press on it it'll refresh the page instead of scrolling down and setting the focus on the editor.

**Comment by JakeBooher** [comment] 2018-02-05 14:16
Duplicate of #434

**Closed by JakeBooher** 2018-02-05 14:16 UTC
Labels: duplicate
