### ISSUE TITLE
UI.X 2.x (Dark) - Arrows in posts are now not blending in!

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#1067] opened 2019-03-15 22:16 UTC
Style Name: UI.X Dark

Style Version: Latest Stable

UI.X Add-on Version: Latest Stable

XenForo Version: Latest Stable

Operating System (and Version): Windows 10/64-bit (Latest Stable)

Browser Name (and Version): Chrome 73/64-bit (Latest Stable)

Does this issue happen in the default XenForo style? No

Summary of issue: When viewing the posts, in the avatar/username area there is a arrow as you'll see in the screenshot. In the last 2 updates it no longer blends in correctly. I like the arrow, and it used to look great.

Upload any screenshots related to the issue below

![uix_dark_arrow_posts_bug](https://user-images.githubusercontent.com/35111972/54464765-68a25100-474e-11e9-90a9-001a2cffd3d5.png)

**Comment by Ian-Hitt** [comment] 2019-03-18 14:52
Duplicate of https://github.com/Audentio/xf2theme-issues/issues/1068 closing

**Closed by Ian-Hitt** 2019-03-18 14:52 UTC
